CREATE TABLE users(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(255) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,name VARCHAR(150) NOT NULL,system_role ENUM('user','race_admin','super_admin') NOT NULL DEFAULT 'user',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE teams(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,created_by BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(created_by) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE team_members(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,team_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NULL,name VARCHAR(150) NOT NULL,phone VARCHAR(40),role ENUM('owner','admin','family','crew') NOT NULL DEFAULT 'family',follows_all_riders TINYINT(1) DEFAULT 1,FOREIGN KEY(team_id) REFERENCES teams(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE team_riders(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,team_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NULL,name VARCHAR(150) NOT NULL,race_number VARCHAR(20),is_managed TINYINT(1) DEFAULT 1,FOREIGN KEY(team_id) REFERENCES teams(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE racing_classes(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) UNIQUE NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE team_rider_classes(rider_id BIGINT UNSIGNED NOT NULL,class_id BIGINT UNSIGNED NOT NULL,PRIMARY KEY(rider_id,class_id),FOREIGN KEY(rider_id) REFERENCES team_riders(id) ON DELETE CASCADE,FOREIGN KEY(class_id) REFERENCES racing_classes(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE team_member_riders(member_id BIGINT UNSIGNED NOT NULL,rider_id BIGINT UNSIGNED NOT NULL,PRIMARY KEY(member_id,rider_id),FOREIGN KEY(member_id) REFERENCES team_members(id) ON DELETE CASCADE,FOREIGN KEY(rider_id) REFERENCES team_riders(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE race_status(id TINYINT UNSIGNED PRIMARY KEY,current_race INT UNSIGNED DEFAULT 1,current_label VARCHAR(150) DEFAULT '',upcoming_race INT UNSIGNED,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO race_status VALUES(1,1,'',2,CURRENT_TIMESTAMP) ON DUPLICATE KEY UPDATE id=id;

CREATE TABLE announcements(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 team_id BIGINT UNSIGNED NULL,
 created_by BIGINT UNSIGNED NOT NULL,
 title VARCHAR(180) NOT NULL,
 body TEXT NOT NULL,
 target_type ENUM('all','class','rider') NOT NULL DEFAULT 'all',
 class_id BIGINT UNSIGNED NULL,
 rider_id BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(team_id) REFERENCES teams(id) ON DELETE CASCADE,
 FOREIGN KEY(created_by) REFERENCES users(id),
 FOREIGN KEY(class_id) REFERENCES racing_classes(id) ON DELETE SET NULL,
 FOREIGN KEY(rider_id) REFERENCES team_riders(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE private_messages(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 sender_user_id BIGINT UNSIGNED NOT NULL,
 recipient_user_id BIGINT UNSIGNED NOT NULL,
 body TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 read_at TIMESTAMP NULL,
 FOREIGN KEY(sender_user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(recipient_user_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX idx_pm_recipient(recipient_user_id,read_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE push_subscriptions(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 platform ENUM('web','android','ios') NOT NULL,
 provider VARCHAR(50) NOT NULL,
 device_key VARCHAR(255) NOT NULL,
 subscription_json JSON NOT NULL,
 enabled TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_device(provider,device_key),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE user_settings(
 user_id BIGINT UNSIGNED PRIMARY KEY,
 announcement_autoplay TINYINT(1) NOT NULL DEFAULT 1,
 notification_sound TINYINT(1) NOT NULL DEFAULT 1,
 private_message_audio TINYINT(1) NOT NULL DEFAULT 0,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
